permalink: /:categories/:title/

exclude: ['bin', 'vendor', 'Gemfile', 'Gemfile.lock', 'Procfile', 'Rakefile', 'unicorn.rb', 'config.ru', 'README.md']

# the order that categories appear in the sidebar
sort_order: ['staff', 'timesheets', 'awards', 'rosters', 'notifications', 'portals', 'training']

asset_bundler:
  compress:
    js: yui
    css: yui
  base_path: /bundles/
  server_url:
  remove_bundled: false